import Config

# Configure the database
config :rubber_duck_storage, RubberDuckStorage.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "rubber_duck_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  # Development-specific settings
  log_level: :debug,
  stacktrace: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :rubber_duck_web, RubberDuckWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "rubber_duck_secret_key_base_for_development_only",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :rubber_duck_web, RubberDuckWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/rubber_duck_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :rubber_duck_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Development-specific configurations for each app

# Core - Enable verbose logging and debugging
config :rubber_duck_core,
  debug_mode: true,
  log_level: :debug,
  # Shorter retention for dev
  conversation_retention_days: 7

# Storage - Faster cache expiry for development
config :rubber_duck_storage,
  cache_ttl: :timer.minutes(5),
  # Enable query logging
  log_queries: true

# Engines - Smaller pools for development
config :rubber_duck_engines,
  engine_pool_size: 3,
  engine_timeout: :timer.seconds(60),
  # Enable all engines in dev
  engines: [
    code_analysis: %{
      enabled: true,
      max_file_size: 1_000_000,
      debug: true
    },
    documentation: %{
      enabled: true,
      cache_results: false  # Disable caching for dev
    },
    testing: %{
      enabled: true,
      test_frameworks: [:ex_unit, :espec],
      verbose: true
    }
  ]

# Web - Additional dev tools
config :rubber_duck_web,
  debug_websockets: true,
  websocket_timeout: :timer.minutes(30)
