defmodule RubberDuck.Repo.Migrations.AddProcessingStatusToConversations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add(:processing_status, :text, null: false, default: "idle")
      add(:processing_started_at, :utc_datetime_usec)
      add(:processing_metadata, :map, default: %{})
    end
  end

  def down do
    alter table(:conversations) do
      remove(:processing_metadata)
      remove(:processing_started_at)
      remove(:processing_status)
    end
  end
end
